name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        env:
          RENDER_SERVICE_ID: rnd_tWdwEYDgQfHBgpSdTpEwOeaEMFDu
          RENDER_API_KEY: srv-d292g3hr0fns73evsv0g
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"
